#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

//Initiate Dotenv
$dotenv = new Dotenv\Dotenv(__DIR__ . '/_files');
$dotenv->load();

$config = require(__DIR__ . '/_files/dummyConsoleConfig.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);